name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv pip install --system -r requirements.txt

      - name: Configure environment variables
        run: |
          echo "SUBSCRIPTION_ID=${{ secrets.SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "RESOURCE_GROUP=${{ secrets.RESOURCE_GROUP }}" >> $GITHUB_ENV
          echo "ML_WORKSPACE_NAME=${{ secrets.ML_WORKSPACE_NAME }}" >> $GITHUB_ENV
          echo "tenant_id=${{ secrets.TENANT_ID }}" >> $GITHUB_ENV
          echo "AZURE_CONNECTION_STRING=${{ secrets.AZURE_CONNECTION_STRING }}" >> $GITHUB_ENV
          echo "AZURE_INPUT_BLOB_PREFIX=${{ secrets.AZURE_INPUT_BLOB_PREFIX }}" >> $GITHUB_ENV
          echo "AZURE_INPUT_CONTAINER_NAME=${{ secrets.AZURE_INPUT_CONTAINER_NAME }}" >> $GITHUB_ENV

      - name: Run DVC pipeline
        run: |
          dvc repro
      